import type { Metadata } from "next";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

import "./globals.scss";

export const metadata: Metadata = {
  title: "千寻",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className="app-container">
        <Header />
        <div className="children">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
